### ISSUE TITLE
Fails to build on Node:7

### ISSUE THREAD

**Issue by codan84** [adamghill/exchanger#11]
This is linked to https://github.com/adamghill/exchanger/issues/3 . I could not reopen the mentioned issue so I have created the new one.  

### From my comment in the other issue:
I can confirm that the problem exists when trying to build exchanger in Docker Node:7 (Linux based docker image). Therefore this is not windows specific!

When using `"exchanger": "~0.1.1"` as dependency I get errors around building the soap dependency. When using the forked version linked by @chuckpearce (`"exchanger": "chuckpearce/exchanger"`) everything builds fine and exchanger can be used with Node:7.

I highly reccomend merging this fork!

**Comment by adamghill** [comment]
Thank you for letting people know about the chuckpearce fork. However, as mentioned in a few other issues, I don't have an Exchange server to test against anymore, so I don't feel comfortable merging in any changes. If anyone wants me to transfer this repo/NPM rights to them, let me know.
