### ISSUE TITLE
fail to install using npm install exchanger

### ISSUE THREAD

**Issue by jareddlc** [adamghill/exchanger#3]
Im trying to install using win7 and i get failed enogit, solved that then im getting enoent. for some reason it says it output a log, but it doesnt. errno 34 Im also getting msbuild error: but ive instaled net 2.0 SDK and it still prompts me with this msg

**Comment by codan84** [comment]
Is this going to be merged?

**Comment by codan84** [comment]
I can confirm that the problem exists when trying to build `exchanger` in Docker Node:7 (Linux based docker image). Therefore this is not windows specific!  

When using `"exchanger": "~0.1.1"` as dependency I get errors around buuilding the `soap` dependency. When using the forked version linked above by @chuckpearce (`"exchanger": "chuckpearce/exchanger"`) everything builds fine and `exchanger` can be used with Node:7.  

I **highly** reccomend merging this fork!
