### ISSUE TITLE
Not installing, under win7, win8, linux

### ISSUE THREAD

**Issue by jareddlc** [adamghill/exchanger#4]
I have tried with 4 different computers and I am not able to install this module. I believe node-soap is the problem see issue #3

**Comment by kemelzaidan** [comment]
It's not installing under recent versions of node. Tested with 6.9.1

**Comment by codan84** [comment]
Linked to https://github.com/adamghill/exchanger/issues/3 . I failed to spot this issue and created a duplicate: https://github.com/adamghill/exchanger/issues/11  
The solution for now is to use forked `chuckpearce/exchanger` instead of this one, until the fork is merged anyway.

**Comment by adamghill** [comment]
Thank you for letting people know about the chuckpearce fork.I don't have an Exchange server to test against anymore. If anyone wants me to transfer this repo/NPM rights to them, let me know.
